CREATE TABLE `COUNTRY` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL UNIQUE,
  `PRESIDENT` VARCHAR(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;